version: '3.8'

services:
  jee:
    image: $CI_REGISTRY_IMAGE/$CI_ENVIRONMENT_SLUG:$VERSION
    networks:
      - traefik-public
    environment:
      TZ: America/Montevideo
      DB_HOST: $PG_HOST
      DB_NAME: $PG_DB
      DB_USER: $PG_USER
      DB_PASS: $PG_PASS
      DB_PORT: $PG_PORT
      LOGSTASH_HOST:
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.${APP_NAME}.rule=Host(`backend.${APP_NAME}.${CI_ENVIRONMENT_SLUG}.softtero.com`)"
        - "traefik.http.routers.${APP_NAME}.entrypoints=http"
        - "traefik.http.routers.${APP_NAME}-secured.rule=Host(`backend.${APP_NAME}.${CI_ENVIRONMENT_SLUG}.softtero.com`)"
        - "traefik.http.routers.${APP_NAME}-secured.entrypoints=https"
        - "traefik.http.routers.${APP_NAME}-secured.tls.certresolver=le"
        - "traefik.http.services.${APP_NAME}.loadbalancer.server.port=8080"
        - "traefik.http.routers.${APP_NAME}.middlewares=${APP_NAME}-redirect"
        - "traefik.http.middlewares.${APP_NAME}-redirect.redirectscheme.scheme=https"
        - "traefik.constraint-label=traefik-public"
      replicas: 2
      placement:
        constraints:
          - node.platform.os == linux
          - node.role == worker
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '1'
          memory: 1024M

networks:
  traefik-public:
    external: true